services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    pintushi.payum_extension.update_payment_state:
        class: Pintushi\Bundle\PayumBundle\Extension\UpdatePaymentStateExtension
        tags:
            - { name: payum.extension, all: true, prepend: true }
        arguments: ['@sm.factory']
