services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\ShippingBundle\:
        resource: '../../{Repository,DataFixtures,Command,Resolver}'

    Pintushi\Bundle\ShippingBundle\Resolver\DefaultShippingMethodResolverInterface: '@Pintushi\Bundle\ShippingBundle\Resolver\DefaultShippingMethodResolver'

    Pintushi\Bundle\ShippingBundle\Repository\ShippingMethodRepositoryInterface: '@Pintushi\Bundle\ShippingBundle\Repository\ShippingMethodRepository'

    Pintushi\Bundle\ShippingBundle\Form\Type\ShippingMethodType:
        arguments:
            - 'Pintushi\Bundle\ShippingBundle\Entity\ShippingMethod'
            - ['pintushi']
        tags:
            - { name: 'form.type' }

    Pintushi\Bundle\ShippingBundle\Form\Type\ShippingMethodCollectionType:
        tags:
            - { name: 'form.type' }
