
Pintushi\Bundle\PromotionBundle\Generator\PromotionCouponGeneratorInstruction:
    constraints:
            -  Pintushi\Bundle\PromotionBundle\Validator\Constraints\CouponPossibleGenerationAmount: { groups: ["pintushi"]}
    properties:
        amount:
            - NotBlank: { groups: ["pintushi"]}
            - Range:
                groups: ["pintushi"]
                min: 1
                minMessage: "pintushi.promotion_coupon_generator_instruction.amount.min"
        usageLimit:
           - Range:
                groups: ["pintushi"]
                min: 1
                minMessage: "pintushi.promotion_coupon_generator_instruction.usage_limit.min"
        codeLength:
           - Range:
                groups: ["pintushi"]
                min: 1
                max: 40
                minMessage: "pintushi.promotion_coupon_generator_instruction.code_length.min"
                maxMessage: "pintushi.promotion_coupon_generator_instruction.code_length.max"
           - NotBlank:
                groups: ["pintushi"]
                message: "pintushi.promotion_coupon_generator_instruction.code_length.not_blank"
