Pintushi\Bundle\PromotionBundle\Entity\Promotion:
    constraints:
        - Pintushi\Bundle\PromotionBundle\Validator\Constraints\PromotionDateRange:
                groups: ["pintushi"]
                message: "pintushi.promotion.end_date_cannot_be_set_prior_start_date"
    properties:
        name:
            - NotBlank:
                groups: ["pintushi"]
                message: 'pintushi.promotion.name.not_blank'
            - Length:
                groups: ["pintushi"]
                min: 2
                max: 255
                minMessage: 'pintushi.promotion.name.not_blank'
                maxMessage: 'pintushi.promotion.name.max_length'
        description:
            - Length:
                groups: ["pintushi"]
                min: 2
                max: 255
                minMessage: 'pintushi.promotion.description.not_blank'
                maxMessage: 'pintushi.promotion.description.max_length'
        actions:
            - Valid:  { groups: ["pintushi"] }
        rules:
            - Valid: { groups: ["pintushi"] }
