Pintushi\Bundle\ReportBundle\Entity\ReportConfigGroup:
    collectionOperations:
           post:
               access_control: is_granted('pintushi_report_config_create')
           get:
               acl_enabled: true
               access_control: is_granted('pintushi_report_config_view')
    itemOperations:
           put:
               access_control: is_granted('pintushi_report_config_edit', object)
           get:
               access_control: is_granted('pintushi_report_config_view', object)
           delete:
               access_control: is_granted('pintushi_report_config_delete', object)
    attributes:
        normalization_context:
            groups: ["read"]
        denormalization_context:
            groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin


Pintushi\Bundle\ReportBundle\Entity\ReportConfigItem:
    collectionOperations:
           post:
               access_control: is_granted('pintushi_report_config_create', object.getGroup())
           get:
               acl_enabled: true
               access_control: is_granted('pintushi_report_config_view', obect.getGroup())
    itemOperations:
           put:
               access_control: is_granted('pintushi_report_config_edit', object.getGroup())
           get:
               access_control: is_granted('pintushi_report_config_view', object.getGroup())
           delete:
               access_control: is_granted('pintushi_report_config_delete', object.getGroup())
    attributes:
        normalization_context:
            groups: ["read"]
        denormalization_context:
            groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin
