Pintushi\Bundle\SmsBundle\Entity\GatewayConfig:
    collectionOperations:
            post:
               access_control: is_granted('pintushi_sms_gateway_config_create')
               route_name: 'api_admin_gateway_config_create'
            get:
               acl_enabled: true
               access_control: is_granted('pintushi_sms_gateway_config_view')
    itemOperations:
           put:
               access_control: is_granted('pintushi_sms_gateway_config_edit', object)
               route_name: 'api_admin_gateway_config_update'
           get:
               access_control: is_granted('pintushi_sms_gateway_config_view', object)
           delete:
               access_control: is_granted('pintushi_sms_gateway_config_delete', object)
    attributes:
        normalization_context:
            groups: ["Detailed"]
        denormalization_context:
            groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin
