services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\LocaleBundle\Model\LocaleSettings: ~

    pintushi_locale.settings: '@Pintushi\Bundle\LocaleBundle\Model\LocaleSettings'

    Pintushi\Bundle\LocaleBundle\Formatter\DateTimeFormatter: ~

    pintushi_locale.formatter.date_time: '@Pintushi\Bundle\LocaleBundle\Formatter\DateTimeFormatter'

    pintushi_locale.formatter.number: '@Pintushi\Bundle\LocaleBundle\Formatter\NumberFormatter'

    Pintushi\Bundle\LocaleBundle\Formatter\NumberFormatter: ~

