Pintushi\Bundle\PromotionBundle\Entity\Promotion:
    attributes:
        id:
            groups: [Default, Detailed]
        name:
            groups: [Default, Detailed]
        startsAt:
            groups: [Detailed]
        endsAt:
            groups: [Detailed]
        usageLimit:
            groups: [Detailed]
        used:
            groups: [Detailed]
        priority:
            groups: [Default, Detailed]
        couponBased:
            groups: [Detailed]
        exclusive:
            groups: [Detailed]
        rules:
            groups: [Detailed]
        actions:
            groups: [Detailed]
        createdAt:
            groups: [Detailed]
        updatedAt:
            groups: [Detailed]
