winzou_state_machine:
    pintushi_shipment:
        class: "%pintushi.model.shipment.class%"
        property_path: state
        graph: sylius_shipment
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            ready: ~
            shipped: ~
            cancelled: ~
        transitions:
            create:
                from: [cart]
                to: ready
            ship:
                from: [ready]
                to: shipped
            cancel:
                from: [ready]
                to: cancelled
