services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\ProductBundle\:
        resource: '../../{Repository,DataFixtures,Command,Provider}'

    pintushi.inventory.order_inventory_operator:
        class: Pintushi\Bundle\ProductBundle\InventoryOperator\OrderInventoryOperator
        decorates: Pintushi\Bundle\InventoryBundle\Operator\OrderInventoryOperator
        arguments:
            - '@pintushi.inventory.order_inventory_operator.inner'
            - '@doctrine.orm.entity_manager'

    Pintushi\Bundle\ProductBundle\Repository\ProductRepositoryInterface: '@Pintushi\Bundle\ProductBundle\Repository\ProductRepository'
