services:
    Pintushi\Bundle\ReviewBundle\Form\Type\ReviewImageType:
        arguments: ['Pintushi\Bundle\ReviewBundle\Entity\OrderReviewImage', ['pintushi']]
        tags:
            - { name: form.type }

    Pintushi\Bundle\ReviewBundle\Form\Type\OrderReviewType:
        arguments:
            - 'Pintushi\Bundle\ReviewBundle\Entity\OrderReview'
            - ['pintushi']
            - '@Overtrue\Pinyin\Pinyin'
        tags:
            - { name: form.type }
