imports:
    - { resource: 'form.yml'}

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\ReviewBundle\:
        resource: '../../{Repository,DataFixtures,Command,Factory}'

    Pintushi\Bundle\ReviewBundle\Factory\ReviewFactory:
        public: true
        arguments:
            - 'Pintushi\Bundle\ReviewBundle\Entity\OrderReview'
