Pintushi\Bundle\SmsBundle\Entity\GatewayConfig:
    attributes:
        id:
            groups: [Default, Detailed]
        priority:
            groups: [Default, Detailed]
        gateway:
            groups: [Default, Detailed]
        configuration:
            groups: [Default, Detailed]
        templates:
            groups: [Default, Detailed]
