parameters:
    pintushi_filter.extension.orm_filter.class:      Pintushi\Bundle\FilterBundle\Grid\Extension\OrmFilterExtension
    pintushi_filter.grid.column_options_guesser.class: Pintushi\Bundle\FilterBundle\Grid\DefaultColumnFilteringOptionsGuesser
    pintushi_filter.provider.datevarsprovider.class: Pintushi\Bundle\FilterBundle\Provider\DateModifierProvider
    pintushi_filter.expression.date.compiler.class:  Pintushi\Bundle\FilterBundle\Expression\Date\Compiler
    pintushi_filter.expression.date.lexer.class:     Pintushi\Bundle\FilterBundle\Expression\Date\Lexer
    pintushi_filter.expression.date.parser.class:    Pintushi\Bundle\FilterBundle\Expression\Date\Parser
    pintushi_filter.builder.many_relation.class:     Pintushi\Bundle\FilterBundle\Datasource\ManyRelationBuilder
    pintushi_filter.builder.many_relation.orm.class: Pintushi\Bundle\FilterBundle\Datasource\Orm\OrmManyRelationBuilder

services:
    pintushi_filter.extension.orm_filter:
        class: '%pintushi_filter.extension.orm_filter.class%'
        arguments:
            - '@pintushi_grid.configuration.provider'
            - '@pintushi_filter.provider.state.filters'
            - '@translator'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_filter.grid.column_options_guesser:
        class: '%pintushi_filter.grid.column_options_guesser.class%'
        tags:
            - { name: pintushi_grid.column_options_guesser }

    pintushi_filter.provider.datemodifierprovider:
        class: '%pintushi_filter.provider.datevarsprovider.class%'

    pintushi_filter.expression.date.parser:
        arguments:
            - '@pintushi_locale.settings'
        class: '%pintushi_filter.expression.date.parser.class%'

    pintushi_filter.expression.date.lexer:
        class: '%pintushi_filter.expression.date.lexer.class%'
        arguments:
            - '@translator'
            - '@pintushi_filter.provider.datemodifierprovider'

    pintushi_filter.expression.date.compiler:
        class: '%pintushi_filter.expression.date.compiler.class%'
        arguments:
            - '@pintushi_filter.expression.date.lexer'
            - '@pintushi_filter.expression.date.parser'

    pintushi_filter.builder.many_relation:
        class: '%pintushi_filter.builder.many_relation.class%'
        calls:
            - [addBuilder, ['@pintushi_filter.builder.many_relation.orm']]

    pintushi_filter.builder.many_relation.orm:
        class: '%pintushi_filter.builder.many_relation.orm.class%'
        arguments:
            - '@doctrine'

    pintushi_filter.utils.date_filter_modifier:
        class: Pintushi\Bundle\FilterBundle\Utils\DateFilterModifier
        arguments:
            - '@pintushi_filter.expression.date.compiler'

    pintushi_filter.provider.state.filters:
        class: 'Pintushi\Bundle\FilterBundle\Provider\State\FiltersStateProvider'
        parent: pintushi_grid.provider.state.abtract
        lazy: true
        arguments:
            - '@pintushi_grid.tools.parameters_helper'

    pintushi_grid.provider.selected_fields.filters:
        class: 'Pintushi\Bundle\FilterBundle\Provider\SelectedFields\SelectedFieldsFromFiltersProvider'
        public: false
        lazy: true
        arguments:
            - '@pintushi_filter.provider.state.filters'
        tags:
            - { name: pintushi_grid.selected_fields_provider }
