parameters:
    pintushi_grid.extension.action.type.navigate.class:    Pintushi\Bundle\GridBundle\Extension\Action\Actions\NavigateAction
    pintushi_grid.extension.action.type.ajax.class:        Pintushi\Bundle\GridBundle\Extension\Action\Actions\AjaxAction
    pintushi_grid.extension.action.type.delete.class:      Pintushi\Bundle\GridBundle\Extension\Action\Actions\DeleteAction
    pintushi_grid.extension.action.type.ajaxdelete.class:  Pintushi\Bundle\GridBundle\Extension\Action\Actions\AjaxDeleteAction
    pintushi_grid.extension.action.type.frontend.class:    Pintushi\Bundle\GridBundle\Extension\Action\Actions\FrontendAction

services:
    pintushi_grid.extension.action.factory:
        class: Pintushi\Bundle\GridBundle\Extension\Action\ActionFactory
        public: false
        arguments:
            - '@service_container'

    pintushi_grid.extension.action.metadata_factory:
        class: Pintushi\Bundle\GridBundle\Extension\Action\ActionMetadataFactory
        public: false
        arguments:
            - '@translator'

    pintushi_grid.extension.action.type.navigate:
        class: '%pintushi_grid.extension.action.type.navigate.class%'
        shared: false
        tags:
            - { name:  pintushi_grid.extension.action.type, type: navigate }

    pintushi_grid.extension.action.type.ajax:
        class: '%pintushi_grid.extension.action.type.ajax.class%'
        shared: false
        tags:
            - { name: pintushi_grid.extension.action.type, type: ajax }

    pintushi_grid.extension.action.type.delete:
        class: '%pintushi_grid.extension.action.type.delete.class%'
        shared: false
        tags:
            - { name: pintushi_grid.extension.action.type, type: delete }

    pintushi_grid.extension.action.type.ajaxdelete:
        class: '%pintushi_grid.extension.action.type.ajaxdelete.class%'
        shared: false
        tags:
            - { name: pintushi_grid.extension.action.type, type: ajaxdelete }

    pintushi_grid.extension.action.type.frontend:
        class: '%pintushi_grid.extension.action.type.frontend.class%'
        shared: false
        tags:
            - { name: pintushi_grid.extension.action.type, type: frontend }

    pintushi_grid.extension.action.type.import:
        class: 'Pintushi\Bundle\GridBundle\Extension\Action\Actions\ImportAction'
        shared: false
        tags:
            - { name: pintushi_grid.extension.action.type, type: import }

    pintushi_grid.extension.action.type.export:
        class: 'Pintushi\Bundle\GridBundle\Extension\Action\Actions\ExportAction'
        shared: false
        tags:
            - { name: pintushi_grid.extension.action.type, type: export }

    pintushi_grid.extension.action.type.trigger_event:
        class: Pintushi\Bundle\GridBundle\Extension\Action\Actions\TriggerEventAction
        shared: false
        tags:
            - { name:  pintushi_grid.extension.action.type, type: trigger-event }
