services:
    pintushi_grid.config.dumper:
        class: Oro\Component\Config\Dumper\CumulativeConfigMetadataDumper
        public: false
        arguments:
            - '%kernel.cache_dir%'
            - '%kernel.debug%'
            - 'pintushi_grid'

    pintushi_grid.event_listener.container_listener:
        class: Pintushi\Bundle\GridBundle\EventListener\ContainerListener
        arguments:
            - '@pintushi_grid.config.dumper'
            - '@pintushi_grid.configuration.provider'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
