parameters:
    pintushi_grid.extension.toolbar.class:          Pintushi\Bundle\GridBundle\Extension\Toolbar\ToolbarExtension
    pintushi_grid.extension.formatter.class:        Pintushi\Bundle\GridBundle\Extension\Formatter\FormatterExtension
    pintushi_grid.extension.orm_pager.class:        Pintushi\Bundle\GridBundle\Extension\Pager\OrmPagerExtension
    pintushi_grid.extension.pager.orm.pager.class:  Pintushi\Bundle\GridBundle\Extension\Pager\Orm\Pager
    pintushi_grid.extension.orm_sorter.class:       Pintushi\Bundle\GridBundle\Extension\Sorter\OrmSorterExtension
    pintushi_grid.extension.inline_editing.class:   Pintushi\Bundle\GridBundle\Extension\InlineEditing\InlineEditingExtension
    pintushi_grid.extension.action.class:           Pintushi\Bundle\GridBundle\Extension\Action\ActionExtension
    pintushi_grid.extension.mass_action.class:      Pintushi\Bundle\GridBundle\Extension\MassAction\MassActionExtension
    pintushi_grid.extension.views.class:            Pintushi\Bundle\GridBundle\Extension\GridViews\GridViewsExtension
    pintushi_grid.extension.export.class:           Pintushi\Bundle\GridBundle\Extension\Export\ExportExtension
    pintushi_grid.extension.gridparams.class:       Pintushi\Bundle\GridBundle\Extension\GridParams\GridParamsExtension
    pintushi_grid.extension.totals.class:           Pintushi\Bundle\GridBundle\Extension\Totals\OrmTotalsExtension
    pintushi_grid.extension.columns.class:          Pintushi\Bundle\GridBundle\Extension\Columns\ColumnsExtension
    pintushi_grid.extension.mode.class:             Pintushi\Bundle\GridBundle\Extension\Mode\ModeExtension
    pintushi_grid.extension.board.class:            Pintushi\Bundle\GridBundle\Extension\Board\BoardExtension
    pintushi_grid.extension.appearance.class:       Pintushi\Bundle\GridBundle\Extension\Appearance\AppearanceExtension

services:
    pintushi_grid.extension.formatter:
        class: '%pintushi_grid.extension.formatter.class%'
        arguments:
            - '@translator'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.orm_pager:
        class: '%pintushi_grid.extension.orm_pager.class%'
        arguments:
            - '@pintushi_grid.extension.pager.orm.pager'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.array_pager:
        class: 'Pintushi\Bundle\GridBundle\Extension\Pager\ArrayPagerExtension'
        arguments:
            - '@pintushi_grid.extension.pager.array.pager'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.pager.orm.pager:
        public: false
        class: '%pintushi_grid.extension.pager.orm.pager.class%'
        arguments:
            - '@pintushi_security.acl_helper'
            - '@pintushi.orm.query_builder.count_query_optimizer'
            - '@pintushi_entity.query_hint_resolver'
            - '@pintushi_grid.orm.query_executor'

    pintushi_grid.extension.pager.array.pager:
        public: false
        class: Pintushi\Bundle\GridBundle\Extension\Pager\ArrayDatasource\ArrayPager

    pintushi_grid.extension.orm_sorter:
        class: '%pintushi_grid.extension.orm_sorter.class%'
        arguments:
            - '@pintushi_grid.provider.state.sorters'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.array_sorter:
        class: Pintushi\Bundle\GridBundle\Extension\Sorter\ArraySorterExtension
        arguments:
            - '@pintushi_grid.provider.state.sorters'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.inline_editing:
        class: '%pintushi_grid.extension.inline_editing.class%'
        arguments:
            - '@pintushi_grid.datagrid.inline_edit_column_options_guesser'
            - '@pintushi_entity.entity_class_name_helper'
            - '@security.authorization_checker'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.action:
        class: '%pintushi_grid.extension.action.class%'
        arguments:
            - '@pintushi_grid.extension.action.factory'
            - '@pintushi_grid.extension.action.metadata_factory'
            - '@security.authorization_checker'
            - '@pintushi_security.owner.ownership_query_helper'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.action.callback_provider:
        class: Pintushi\Bundle\GridBundle\Extension\Action\DatagridCallbackActionProvider
        tags:
            - { name: pintushi_grid.extension.action.provider, priority: 255 }

    pintushi_grid.extension.mass_delete_action:
        class: Pintushi\Bundle\GridBundle\Extension\MassAction\DeleteMassActionExtension
        arguments:
            - '@pintushi_entity.doctrine_helper'
            - '@pintushi_entity.orm.entity_class_resolver'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.mass_action:
        class: '%pintushi_grid.extension.mass_action.class%'
        arguments:
            - '@pintushi_grid.extension.mass_action.factory'
            - '@pintushi_grid.extension.mass_action.metadata_factory'
            - '@security.authorization_checker'
            - '@security.csrf.token_manager'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.toolbar:
        class: '%pintushi_grid.extension.toolbar.class%'
        arguments:
            - '@pintushi_config.user'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.views:
        class: '%pintushi_grid.extension.views.class%'
        arguments:
            - '@event_dispatcher'
            - '@security.authorization_checker'
            - '@pintushi_security.token_accessor'
            - '@translator'
            - '@doctrine'
            - '@pintushi_security.acl_helper'
            - '@pintushi_grid.grid_view.manager.link'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.export:
        class: '%pintushi_grid.extension.export.class%'
        arguments:
            - '@translator'
            - '@security.authorization_checker'
            - '@security.token_storage'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.gridparams:
        class: '%pintushi_grid.extension.gridparams.class%'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.totals:
        class: '%pintushi_grid.extension.totals.class%'
        arguments:
            - '@translator'
            - '@pintushi_locale.formatter.number'
            - '@pintushi_locale.formatter.date_time'
            - '@pintushi_security.acl_helper'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.columns:
        class: '%pintushi_grid.extension.columns.class%'
        arguments:
            - '@pintushi_grid.provider.state.columns'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.mode:
        class: '%pintushi_grid.extension.mode.class%'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.precise_order_by:
        class: Pintushi\Bundle\GridBundle\Extension\Sorter\HintExtension
        arguments:
            - '@pintushi_entity.query_hint_resolver'
            - 'HINT_PRECISE_ORDER_BY'
            - -261
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.nulls_order:
        class: Pintushi\Bundle\GridBundle\Extension\Sorter\HintExtension
        arguments:
            - '@pintushi_entity.query_hint_resolver'
            - '@=constant("Oro\\Component\\DoctrineUtils\\ORM\\SqlWalker::HINT_DISABLE_ORDER_BY_MODIFICATION_NULLS")'
            - -300
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.field_acl:
        class: Pintushi\Bundle\GridBundle\Extension\FieldAcl\FieldAclExtension
        arguments:
            - '@security.authorization_checker'
            - '@pintushi_entity_config.config_manager'
            - '@pintushi_security.owner.ownership_query_helper'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.board:
        class: '%pintushi_grid.extension.board.class%'
        arguments:
            - '@security.authorization_checker'
            - '@translator'
            - '@pintushi_grid.datagrid.board.configuration'
            - '@pintushi_entity.entity_class_name_helper'
            - '@pintushi_entity.orm.entity_class_resolver'
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.appearance:
        class: '%pintushi_grid.extension.appearance.class%'
        arguments:
            - '@pintushi_grid.datagrid.appearance.configuration'
            - '@translator'
        tags:
            - { name: pintushi_grid.extension }

    # pintushi_grid.extension.feature:
    #     class: Pintushi\Bundle\GridBundle\Extension\Feature\FeatureExtension
    #     arguments:
    #         - '@oro_featuretoggle.checker.feature_checker'
    #     tags:
    #         - { name: pintushi_grid.extension }
