parameters:
    pintushi_grid.extension.toolbar.class:          Pintushi\Bundle\GridBundle\Extension\Toolbar\ToolbarExtension
    pintushi_grid.extension.orm_sorter.class:       Pintushi\Bundle\GridBundle\Extension\Sorter\OrmSorterExtension
    pintushi_grid.extension.views.class:            Pintushi\Bundle\GridBundle\Extension\GridViews\GridViewsExtension
    pintushi_grid.extension.gridparams.class:       Pintushi\Bundle\GridBundle\Extension\GridParams\GridParamsExtension
    pintushi_grid.extension.mode.class:             Pintushi\Bundle\GridBundle\Extension\Mode\ModeExtension
    pintushi_grid.extension.appearance.class:       Pintushi\Bundle\GridBundle\Extension\Appearance\AppearanceExtension
    pintushi_grid.extension.column_state.class:     Pintushi\Bundle\GridBundle\Extension\Columns\ColumnStateExtension
    pintushi_grid.extension.columns.class:          Pintushi\Bundle\GridBundle\Extension\Columns\ColumnsExtension

services:
    pintushi_grid.extension.orm_sorter:
        class: '%pintushi_grid.extension.orm_sorter.class%'
        arguments:
            - '@pintushi_grid.provider.state.sorters'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.array_sorter:
        class: Pintushi\Bundle\GridBundle\Extension\Sorter\ArraySorterExtension
        arguments:
            - '@pintushi_grid.provider.state.sorters'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.pager:
        class: Pintushi\Bundle\GridBundle\Extension\Pager\PagerfantaExtension
        arguments:
            - '@pintushi_grid.provider.state.sorters'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.toolbar:
        class: '%pintushi_grid.extension.toolbar.class%'
        arguments:
            - '@pintushi_config.user'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.views:
        class: '%pintushi_grid.extension.views.class%'
        arguments:
            - '@event_dispatcher'
            - '@security.authorization_checker'
            - '@pintushi_security.token_accessor'
            - '@translator'
            - '@doctrine'
            - '@pintushi_security.acl_helper'
            - '@pintushi_grid.grid_view.manager.link'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.gridparams:
        class: '%pintushi_grid.extension.gridparams.class%'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.mode:
        class: '%pintushi_grid.extension.mode.class%'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.precise_order_by:
        class: Pintushi\Bundle\GridBundle\Extension\Sorter\HintExtension
        arguments:
            - '@pintushi_entity.query_hint_resolver'
            - 'HINT_PRECISE_ORDER_BY'
            - -261
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.nulls_order:
        class: Pintushi\Bundle\GridBundle\Extension\Sorter\HintExtension
        arguments:
            - '@pintushi_entity.query_hint_resolver'
            - '@=constant("Oro\\Component\\DoctrineUtils\\ORM\\SqlWalker::HINT_DISABLE_ORDER_BY_MODIFICATION_NULLS")'
            - -300
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.appearance:
        class: '%pintushi_grid.extension.appearance.class%'
        arguments:
            - '@pintushi_grid.grid.appearance.configuration'
            - '@translator'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.column_state:
        class: '%pintushi_grid.extension.column_state.class%'
        arguments:
            - '@pintushi_grid.provider.state.columns'
        tags:
            - { name: pintushi_grid.extension }

    pintushi_grid.extension.columns:
        class: '%pintushi_grid.extension.columns.class%'
        arguments:
            - '@translator'
        tags:
            - { name: pintushi_grid.extension }
