services:
    pintushi_grid.tools.parameters_helper:
        class: 'Pintushi\Bundle\GridBundle\Tools\GridParametersHelper'
        public: false

    pintushi_grid.provider.state.abtract:
        class: 'Pintushi\Bundle\GridBundle\Provider\State\AbstractStateProvider'
        abstract: true
        public: false
        arguments:
            - '@pintushi_grid.grid_view.manager'
            - '@pintushi_security.token_accessor'

    pintushi_grid.provider.state.columns:
        class: 'Pintushi\Bundle\GridBundle\Provider\State\ColumnsStateProvider'
        parent: pintushi_grid.provider.state.abtract
        lazy: true
        arguments:
            - '@pintushi_grid.tools.parameters_helper'

    pintushi_grid.provider.state.sorters:
        class: 'Pintushi\Bundle\GridBundle\Provider\State\SortersStateProvider'
        parent: pintushi_grid.provider.state.abtract
        lazy: true
        arguments:
            - '@pintushi_grid.tools.parameters_helper'

    pintushi_grid.provider.selected_fields:
        class: 'Pintushi\Bundle\GridBundle\Provider\SelectedFields\SelectedFieldsProvider'
        public: false
        lazy: true

    pintushi_grid.provider.selected_fields.columns:
        class: 'Pintushi\Bundle\GridBundle\Provider\SelectedFields\SelectedFieldsFromColumnsProvider'
        public: false
        lazy: true
        arguments:
            - '@pintushi_grid.provider.state.columns'
        tags:
            - { name: pintushi_grid.selected_fields_provider }

    pintushi_grid.provider.selected_fields.sorters:
        class: 'Pintushi\Bundle\GridBundle\Provider\SelectedFields\SelectedFieldsFromSortersProvider'
        public: false
        lazy: true
        arguments:
            - '@pintushi_grid.provider.state.sorters'
        tags:
            - { name: pintushi_grid.selected_fields_provider }
