services:
    pintushi_grid.block_type_extension.taggable_datagrid:
        class: Pintushi\Bundle\GridBundle\Layout\Block\Extension\TaggableDatagridExtension
        tags:
            - { name: layout.block_type_extension, alias: datagrid }
