parameters:
    pintushi_grid.extension.mass_action.handler.delete.class:  Pintushi\Bundle\GridBundle\Extension\MassAction\DeleteMassActionHandler
    pintushi_grid.mass_action.parameters_parser.class:         Pintushi\Bundle\GridBundle\Extension\MassAction\MassActionParametersParser
    pintushi_grid.mass_action.dispatcher.class:                Pintushi\Bundle\GridBundle\Extension\MassAction\MassActionDispatcher

    pintushi_grid.extension.mass_action.type.ajax.class:       Pintushi\Bundle\GridBundle\Extension\MassAction\Actions\Ajax\AjaxMassAction
    pintushi_grid.extension.mass_action.type.delete.class:     Pintushi\Bundle\GridBundle\Extension\MassAction\Actions\Ajax\DeleteMassAction

    pintushi_grid.extension.mass_action.type.redirect.class:   Pintushi\Bundle\GridBundle\Extension\MassAction\Actions\Redirect\RedirectMassAction
    pintushi_grid.extension.mass_action.type.widget.class:     Pintushi\Bundle\GridBundle\Extension\MassAction\Actions\Widget\WidgetMassAction
    pintushi_grid.extension.mass_action.type.window.class:     Pintushi\Bundle\GridBundle\Extension\MassAction\Actions\Widget\WindowMassAction
    pintushi_grid.extension.mass_action.type.frontend.class:     Pintushi\Bundle\GridBundle\Extension\MassAction\Actions\FrontendMassAction

services:
    pintushi_grid.extension.mass_action.factory:
        class: Pintushi\Bundle\GridBundle\Extension\MassAction\MassActionFactory
        public: false
        arguments:
            - '@service_container'

    pintushi_grid.extension.mass_action.metadata_factory:
        class: Pintushi\Bundle\GridBundle\Extension\MassAction\MassActionMetadataFactory
        public: false
        arguments:
            - '@pintushi_grid.extension.action.metadata_factory'

    pintushi_grid.extension.mass_action.handler.delete:
        class: '%pintushi_grid.extension.mass_action.handler.delete.class%'
        arguments:
            - '@doctrine'
            - '@translator'
            - '@security.authorization_checker'
            - '@pintushi_grid.extension.mass_action.actions.ajax.mass_delete_limiter'
            - '@request_stack'

    pintushi_grid.mass_action.parameters_parser:
        class: '%pintushi_grid.mass_action.parameters_parser.class%'

    pintushi_grid.mass_action.helper:
        class: Pintushi\Bundle\GridBundle\Extension\MassAction\MassActionHelper
        public: false
        arguments:
            - '@service_container'

    pintushi_grid.mass_action.dispatcher:
        class: '%pintushi_grid.mass_action.dispatcher.class%'
        arguments:
            - '@pintushi_grid.datagrid.manager'
            - '@pintushi_grid.mass_action.helper'
            - '@pintushi_grid.mass_action.parameters_parser'
            - '@pintushi_grid.extension.mass_action.iterable_result_factory_registry'

    pintushi_grid.extension.mass_action.type.ajax:
        class: '%pintushi_grid.extension.mass_action.type.ajax.class%'
        shared: false
        tags:
            - { name:  pintushi_grid.extension.mass_action.type, type: ajax }

    pintushi_grid.extension.mass_action.type.delete:
        class: '%pintushi_grid.extension.mass_action.type.delete.class%'
        shared: false
        tags:
            - { name:  pintushi_grid.extension.mass_action.type, type: delete }

    pintushi_grid.extension.mass_action.type.redirect:
        class: '%pintushi_grid.extension.mass_action.type.redirect.class%'
        shared: false
        tags:
            - { name:  pintushi_grid.extension.mass_action.type, type: redirect }

    pintushi_grid.extension.mass_action.type.widget:
        class: '%pintushi_grid.extension.mass_action.type.widget.class%'
        shared: false
        tags:
            - { name:  pintushi_grid.extension.mass_action.type, type: widget }

    pintushi_grid.extension.mass_action.type.window:
        class: '%pintushi_grid.extension.mass_action.type.window.class%'
        shared: false
        tags:
            - { name:  pintushi_grid.extension.mass_action.type, type: window }

    pintushi_grid.extension.mass_action.type.massedit:
        class: Pintushi\Bundle\GridBundle\Extension\MassAction\Actions\Widget\MassEdit\MassEditAction
        shared: false
        tags:
            - { name:  pintushi_grid.extension.mass_action.type, type: massedit }

    pintushi_grid.extension.mass_action.type.frontend:
        class: '%pintushi_grid.extension.mass_action.type.frontend.class%'
        shared: false
        tags:
            - { name:  pintushi_grid.extension.mass_action.type, type: frontend }

    pintushi_grid.extension.mass_action.actions.ajax.mass_delete_limiter:
        class: Pintushi\Bundle\GridBundle\Extension\MassAction\Actions\Ajax\MassDelete\MassDeleteLimiter
        arguments:
            - '@pintushi_security.acl_helper'

    pintushi_grid.extension.mass_action.iterable_result_factory:
        class: Pintushi\Bundle\GridBundle\Extension\MassAction\IterableResultFactory
        public: false
        arguments:
            - '@pintushi_security.acl_helper'
        tags:
            - { name: pintushi_grid.extension.mass_action.iterable_result_factory }

    pintushi_grid.extension.mass_action.iterable_result_factory_registry:
        class: Pintushi\Bundle\GridBundle\Extension\MassAction\IterableResultFactoryRegistry
        public: false
