parameters:
    pintushi_entity_config.entity.entity_field.class:                Pintushi\Bundle\EntityConfigBundle\Entity\FieldConfigModel
    pintushi_entity_config.config_manager.class:                     Pintushi\Bundle\EntityConfigBundle\Config\ConfigManager
    pintushi_entity_config.config_model_manager.class:               Pintushi\Bundle\EntityConfigBundle\Config\ConfigModelManager
    pintushi_entity_config.tools.command_executor.class:             Pintushi\Bundle\EntityConfigBundle\Tools\CommandExecutor
    pintushi_entity_config.config_loader.class:                      Pintushi\Bundle\EntityConfigBundle\Tools\ConfigLoader
    pintushi_entity_config.helper.entity_config.class:               Pintushi\Bundle\EntityConfigBundle\Helper\EntityConfigHelper

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\EntityConfigBundle\:
        resource: '../../{Repository,DataFixtures,Controller,Command}'

    pintushi_entity_config.entity_manager_bag:
        class: Pintushi\Bundle\EntityConfigBundle\Config\EntityManagerBag
        arguments:
            - '@doctrine'

    pintushi_entity_config.config_manager:
        class: '%pintushi_entity_config.config_manager.class%'
        arguments:
            - '@event_dispatcher'
            - '@pintushi_entity_config.metadata.annotation_metadata_factory'
            - '@pintushi_entity_config.config_model_manager'
            - '@pintushi_entity_config.cache'

    Pintushi\Bundle\EntityConfigBundle\Config\ConfigManager: '@pintushi_entity_config.config_manager'

    pintushi_entity_config.config_model_lock_object:
        class: Pintushi\Bundle\EntityConfigBundle\Config\LockObject

    pintushi_entity_config.config_model_manager:
        class: '%pintushi_entity_config.config_model_manager.class%'
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@pintushi_entity_config.config_model_lock_object'
            - '@pintushi_entity_config.database_checker'

    pintushi_entity_config.helper.entity_config:
        class: '%pintushi_entity_config.helper.entity_config.class%'
        arguments:
            - '@pintushi_entity_config.provider.entity'
            - '@pintushi.acl.group_provider.chain'

    pintushi_entity_config.tools.command_executor:
        class: '%pintushi_entity_config.tools.command_executor.class%'
        arguments:
            - '%kernel.root_dir%/console'
            - '%kernel.environment%'
            - '@oro_cache.oro_data_cache_manager'

    pintushi_entity_config.config_loader:
        public: true
        class: '%pintushi_entity_config.config_loader.class%'
        arguments:
            - '@pintushi_entity_config.config_manager'
            - '@pintushi_entity_config.entity_manager_bag'

    pintushi_entity_config.cache:
        class: Pintushi\Bundle\EntityConfigBundle\Config\ConfigCache
        arguments:
            - '@pintushi_entity_config.config_cache_impl'
            - '@pintushi_entity_config.model_cache_impl'
            - '%kernel.debug%'

    pintushi_entity_config.config_cache_impl:
        autowire: false
        autoconfigure: false
        public: false
        parent: doctrine_cache.abstract.chain
        calls:
            - [setNamespace, [ 'pintushi_entity_config' ] ]

    pintushi_entity_config.model_cache_impl:
        public: false
        autowire: false
        autoconfigure: false
        parent: doctrine_cache.abstract.chain
        calls:
            - [setNamespace, [ 'pintushi_entity_config_model' ] ]

    pintushi_entity_config.config_cache_warmer:
        class: Pintushi\Bundle\EntityConfigBundle\Config\ConfigCacheWarmer
        arguments:
            - '@pintushi_entity_config.config_manager'
            - '@pintushi_entity_config.cache'
            - '@pintushi_entity_config.config_model_lock_object'
            - '@pintushi_entity_config.entity_manager_bag'

    pintushi_entity_config.cache.warmer:
        class: Pintushi\Bundle\EntityConfigBundle\Cache\CacheWarmer
        arguments:
            - '@pintushi_entity_config.config_cache_warmer'
        tags:
            - { name: kernel.cache_warmer, priority: 28 }

    pintushi_entity_config.provider.serialized_field_provider:
        class: 'Pintushi\Bundle\EntityConfigBundle\Provider\SerializedFieldProvider'

    pintushi_entity_config.config.config_helper:
        class: 'Pintushi\Bundle\EntityConfigBundle\Config\ConfigHelper'
        arguments:
            - '@pintushi_entity_config.config_manager'

    pintushi_entity_config.provider.extend_entity_config_provider:
        class: 'Pintushi\Bundle\EntityConfigBundle\Provider\ExtendEntityConfigProvider'
        arguments:
            - '@pintushi_entity_config.config_manager'

    pintushi_entity_config.database_checker:
        class: Pintushi\Bundle\EntityConfigBundle\Config\ConfigDatabaseChecker
        arguments:
            - '@pintushi_entity_config.config_model_lock_object'
            - '@doctrine'
            - ['pintushi_entity_config', 'pintushi_entity_config_field', 'pintushi_entity_config_index_value']
        tags:
            - { name: pintushi_entity.database_checker }


