winzou_state_machine:
    pintushi_order_payment:
        class: 'Pintushi\Bundle\OrderBundle\Entity\Order'
        property_path: paymentState
        graph: pintushi_order_payment
        state_machine_class: 'Pintushi\Bundle\OrderBundle\StateMachine\StateMachine'
        states:
            cart: ~
            awaiting_payment: ~
            partially_paid: ~
            cancelled: ~
            paid: ~
            partially_refunded: ~
            refunded: ~
        transitions:
            request_payment:
                from: [cart]
                to: awaiting_payment
            cancel:
                from: [awaiting_payment]
                to: cancelled
            pay:
                from: [awaiting_payment]
                to: paid
            refund:
                from: [paid]
                to: refunded
        callbacks:
            after:
                pintushi_order_paid:
                    on: ['pay']
                    do: ['@Pintushi\Bundle\InventoryBundle\Operator\OrderInventoryOperator', 'sell']
                    args: ['object']
                pintushi_resolve_state:
                    on: ['pay']
                    do: ['@Pintushi\Bundle\OrderBundle\StateResolver\OrderStateResolver', 'resolve']
                    args: ['object']
                pintushi_order_refund:
                    on: ['refund']
                    do: ['@sm.callback.cascade_transition', 'apply']
                    args: ['object', 'event', "'cancel'", "'pintushi_order'"]
