winzou_state_machine:
    pintushi_order_review:
        class: 'Pintushi\Bundle\ReviewBundle\Entity\OrderReview'
        property_path: status
        graph: pintushi_order_review
        state_machine_class: 'Pintushi\Bundle\OrderBundle\StateMachine\StateMachine'
        states:
            new: ~
            accepted: ~
            rejected: ~
        transitions:
            accept:
                from: [new]
                to: accepted
            reject:
                from: [new]
                to: rejected

