winzou_state_machine:
    pintushi_order_shipping:
        class: 'Pintushi\Bundle\OrderBundle\Entity\Order'
        property_path: shippingState
        graph: pintushi_order_shipping
        state_machine_class: 'Pintushi\Bundle\OrderBundle\StateMachine\StateMachine'
        states:
            cart: ~
            ready: ~
            cancelled: ~
            partially_shipped: ~
            shipped: ~
        transitions:
            request_shipping:
                from: [cart]
                to: ready
            cancel:
                from: [ready]
                to: cancelled
            ship:
                from: [ready]
                to: shipped
        callbacks:
            after:
                pintushi_resolve_state:
                    on: ['ship']
                    do: ['@Pintushi\Bundle\OrderBundle\StateResolver\OrderStateResolver', 'resolve']
                    args: ['object']
