winzou_state_machine:
    pintushi_order:
        class: 'Pintushi\Bundle\OrderBundle\Entity\Order'
        property_path: state
        graph: pintushi_order
        state_machine_class: 'Pintushi\Bundle\OrderBundle\StateMachine\StateMachine'
        states:
            cart: ~
            new: ~
            cancelled: ~
            fulfilled: ~
        transitions:
            create:
                from: [cart]
                to: new
            cancel:
                from: [new]
                to: cancelled
            fulfill:
                from: [new]
                to: fulfilled
        callbacks:
            before:
                pintushi_process_order:
                    on: ["create"]
                    do: ['@Pintushi\Component\Order\Processor\OrderProcessorInterface', "process"]
                    args: ["object"]
                pintushi_assign_number:
                    on: ['create']
                    do: ['@Pintushi\Bundle\OrderBundle\NumberAssigner\OrderNumberAssigner', 'assignNumber']
                    args: ['object']
                pintushi_assign_token:
                    on: ["create"]
                    do: ['@Pintushi\Bundle\OrderBundle\TokenAssigner\UniqueIdBasedOrderTokenAssigner', "assignTokenValueIfNotSet"]
                    args: ["object"]
            after:
                pintushi_request_shipping:
                    on: ['create']
                    do: ['@sm.callback.cascade_transition', 'apply']
                    args: ['object', 'event', "'request_shipping'", "'pintushi_order_shipping'"]
                pintushi_request_payment:
                    on: ['create']
                    do: ['@sm.callback.cascade_transition', 'apply']
                    args: ['object', 'event', "'request_payment'", "'pintushi_order_payment'"]
                pintushi_create_payment:
                    on: ['create']
                    do: ['@sm.callback.cascade_transition', 'apply']
                    args: ['object.getPayment()', 'event', "'create'", "'pintushi_payment'"]
                pintushi_create_shipment:
                    on: ['create']
                    do: ['@sm.callback.cascade_transition', 'apply']
                    args: ['object.getShipment()', 'event', "'create'", "'pintushi_shipment'"]
                pintushi_hold_inventory:
                    on: ['create']
                    do: ['@Pintushi\Bundle\InventoryBundle\Operator\OrderInventoryOperator', 'hold']
                    args: ['object']
                pintushi_increment_promotions_usages:
                    on: ['create']
                    do: ['@Pintushi\Bundle\PromotionBundle\Modifier\OrderPromotionsUsageModifier', 'increment']
                    args: ['object']
                pintushi_cancel_payment:
                    on: ['cancel']
                    do: ['@sm.callback.cascade_transition', 'apply']
                    args: ['object.getPayment()', 'event', "'cancel'", "'pintushi_payment'"]
                pintushi_cancel_shipment:
                    on: ['cancel']
                    do: ['@sm.callback.cascade_transition', 'apply']
                    args: ['object.getShipment()', 'event', "'cancel'", "'pintushi_shipment'"]
                pintushi_cancel_order_payment:
                    on: ['cancel']
                    do: ['@sm.callback.cascade_transition', 'apply']
                    args: ['object', 'event', "'cancel'", "'pintushi_order_payment'"]
                pintushi_cancel_order_shipment:
                    on: ['cancel']
                    do: ['@sm.callback.cascade_transition', 'apply']
                    args: ['object', 'event', "'cancel'", "'pintushi_order_shipping'"]
                pintushi_cancel_order:
                    on: ['cancel']
                    do: ['@pintushi.inventory.order_inventory_operator', 'cancel']
                    args: ['object']
                pintushi_decrement_promotions_usages:
                    on: ['cancel']
                    do: ['@Pintushi\Bundle\PromotionBundle\Modifier\OrderPromotionsUsageModifier', 'decrement']
                    args: ['object']
