Pintushi\Bundle\ShippingBundle\Entity\ShippingMethod:
    collectionOperations:
           post:
               access_control: is_granted('pintushi_shipping_method_create')
           get:
               acl_enabled: true
               access_control: is_granted('pintushi_shipping_method_view')
    itemOperations:
           put:
               access_control: is_granted('pintushi_shipping_method_edit', object)
           get:
               access_control: is_granted('pintushi_shipping_method_view', object)
           delete:
               access_control: is_granted('pintushi_shipping_method_delete', object)
    attributes:
        normalization_context:
            groups: ["read"]
        denormalization_context:
            groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin
