Pintushi\Bundle\LocationBundle\Entity\Location:
    attributes:
        code:
            groups: ['read', 'write']
        name:
            groups: ['read', 'write']
        parent:
            groups: ['Details', 'write']
            max_depth: 1
        abbr:
            groups: ['read', 'write']
        postCode:
            groups: ['read', 'write']
        areaCode:
            groups: ['read', 'write']
        pinyin:
            groups: ['read', 'write']
