Pintushi\Bundle\MaintenanceBundle\Entity\Service:
    attributes:
        id:
            groups: ['read', 'Default', 'Simple', 'Details']
        name:
            groups: ['read', 'write', 'Simple', 'Details']
        description:
            groups: ['read', 'write', 'Simple', 'Details']
        organization:
            groups: ['read', 'write']
        enabled:
            groups: ['read', 'write', "Details"]
        position:
            groups: ['read', 'write', 'Details']
        group:
            groups: ['write', 'read']
        price:
            groups: ['read', 'write', 'Details']

