acls:
    pintushi_service_create:
        type: entity
        class: Pintushi\Bundle\MaintenanceBundle\Entity\Service
        label: '添加保养服务'
        permission: 'CREATE'
        category: "maintenance"

    pintushi_service_view:
        type: entity
        class: Pintushi\Bundle\MaintenanceBundle\Entity\Service
        label: '查看保养服务'
        permission: 'VIEW'
        category: "maintenance"

    pintushi_service_delete:
        type: entity
        class: Pintushi\Bundle\MaintenanceBundle\Entity\Service
        label: '查看保养服务'
        permission: 'DELETE'
        category: "maintenance"

    pintushi_service_edit:
        type: entity
        class: Pintushi\Bundle\MaintenanceBundle\Entity\Service
        label: '编辑保养服务'
        permission: 'EDIT'
        category: "maintenance"

    pintushi_service_group_create:
        type: entity
        class: Pintushi\Bundle\MaintenanceBundle\Entity\ServiceGroup
        label: '添加保养服务'
        permission: 'CREATE'
        category: "maintenance"

    pintushi_service_group_view:
        type: entity
        class: Pintushi\Bundle\MaintenanceBundle\Entity\ServiceGroup
        label: '查看保养服务'
        permission: 'VIEW'
        category: "maintenance"

    pintushi_service_group_delete:
        type: entity
        class: Pintushi\Bundle\MaintenanceBundle\Entity\ServiceGroup
        label: '查看保养服务'
        permission: 'DELETE'
        category: "maintenance"

    pintushi_service_group_edit:
        type: entity
        class: Pintushi\Bundle\MaintenanceBundle\Entity\ServiceGroup
        label: '编辑保养服务'
        permission: 'EDIT'
        category: "maintenance"

    pintushi_service_block_create:
        type: entity
        class: Pintushi\Bundle\MaintenanceBundle\Entity\ServiceBlock
        label: '添加Service Block'
        permission: 'CREATE'
        category: "maintenance"

    pintushi_service_block_view:
        type: entity
        class: Pintushi\Bundle\MaintenanceBundle\Entity\ServiceBlock
        label: '查看Service Block'
        permission: 'VIEW'
        category: "maintenance"

    pintushi_service_block_delete:
        type: entity
        class: Pintushi\Bundle\MaintenanceBundle\Entity\ServiceBlock
        label: '查看Service Block'
        permission: 'DELETE'
        category: "maintenance"

    pintushi_service_block_edit:
        type: entity
        class: Pintushi\Bundle\MaintenanceBundle\Entity\ServiceBlock
        label: '编辑Service Block'
        permission: 'EDIT'
        category: "maintenance"
