api_sms_global_verification_code_send:
     path: '/shop/sms/global/send'
     controller: pintushi.global.action.verification_code_send
     methods: 'GET'
     defaults:
          _api_respond: 1

api_sms_system_verification_code_send:
     path: '/sms/system/send'
     controller: pintushi.system.action.verification_code_send
     methods: 'GET'
     defaults:
          _api_respond: 1
