imports:
    - { resource: 'forms.yml'}
    - { resource: 'security.yml'}

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\SmsBundle\EventListener\VerificationCodeListener: ~

    Pintushi\Bundle\SmsBundle\:
        resource: '../../{Repository,DataFixtures,Command}'

    pintushi.phone_number_verification.cache:
        public: false
        autowire: false
        autoconfigure: false
        parent: doctrine_cache.abstract.chain
        calls:
            - [ setNamespace, [ 'pintushi_phone_number_verification' ]]

    Pintushi\Bundle\SmsBundle\Verification\SmsCaptchaSenderFactory:
        arguments:
            - '@pintushi.phone_number_verification.cache'

    Pintushi\Bundle\SmsBundle\Builder\MessageTemplateGatewayConfigBuilder:
        arguments:
            - '@Pintushi\Bundle\SmsBundle\Repository\GatewayConfigRepository'
            - 'verification_code'

    Pintushi\Bundle\SmsBundle\Builder\MessageTemplateConfigurationBuilder:
        arguments:
            - '%pintushi.sms_templates%'
            - 'verification_code'

    pintushi.system.phone_number_verification:
        class: Pintushi\Bundle\SmsBundle\Verification\SmsCaptchaSender
        factory: Pintushi\Bundle\SmsBundle\Verification\SmsCaptchaSenderFactory:create
        arguments:
            - "@pintushi.sms"
        calls:
            - [ setMessageTemplateBuilder, ['@Pintushi\Bundle\SmsBundle\Builder\MessageTemplateConfigurationBuilder'] ]

    Pintushi\Bundle\SmsBundle\Verification\SmsCaptchaValidator:
        arguments: ['@pintushi.phone_number_verification.cache']

# organization sms
    # pintushi.organization_sms_factory:
    #     class: Pintushi\Bundle\SmsBundle\Factory\SmsFactory

    # pintushi.organization.action.verification_code_send:
    #     class: Pintushi\Bundle\SmsBundle\Controller\SendVerificationCodeAction
    #     arguments:
    #         - '@pintushi.organization.phone_number_verification'


    # pintushi.organization.phone_number_verification:
    #     class: Pintushi\Bundle\SmsBundle\Verification\SmsCaptchaSender
    #     factory: Pintushi\Bundle\SmsBundle\Verification\SmsCaptchaSenderFactory:create
    #     arguments:
    #         - "@=service('pintushi.organization_sms_factory').create()"
    #     calls:
    #         - [ setMessageTemplateBuilder, ['@Pintushi\Bundle\SmsBundle\Builder\MessageTemplateGatewayConfigBuilder'] ]
