Pintushi\Bundle\BlockBundle\Entity\BlockContainer:
    attributes:
        id:
            groups: ['read', 'Details']
        name:
            groups: ['read', 'write', 'Details']
        organization:
            groups: ['read', 'write']
        title:
            groups: ['read', 'write', 'Details']
        blocks:
            groups: ['read', 'write',  'Details']
