acls:
    pintushi_sms_gateway_config_create:
        type: entity
        class: Pintushi\Bundle\SmsBundle\Entity\GatewayConfig
        label: '创建短信配置'
        permission: 'CREATE'
        category: "sms_gateway_config"

    pintushi_sms_gateway_config_view:
        type: entity
        class: Pintushi\Bundle\SmsBundle\Entity\GatewayConfig
        label: '查看短信配置'
        permission: 'VIEW'
        category: "sms_gateway_config"

    pintushi_sms_gateway_config_delete:
        type: entity
        class: Pintushi\Bundle\SmsBundle\Entity\GatewayConfig
        label: '查看短信配置'
        permission: 'DELETE'
        category: "sms_gateway_config"

    pintushi_sms_gateway_config_edit:
        type: entity
        class: Pintushi\Bundle\SmsBundle\Entity\GatewayConfig
        label: '编辑短信配置'
        permission: 'EDIT'
        category: "sms_gateway_config"
