Pintushi\Bundle\BlockBundle\Entity\BlockContainer:
    collectionOperations:
           post:
               access_control: is_granted('pintushi_block_create')
           get:
               acl_enabled: true
               access_control: is_granted('pintushi_block_view')
    itemOperations:
           put:
               access_control: is_granted('pintushi_block_edit', object)
           get:
               access_control: is_granted('pintushi_block_view', object)
           delete:
               access_control: is_granted('pintushi_block_delete', object)
    attributes:
        normalization_context:
            groups: ["read"]
        denormalization_context:
            groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin
