ApiPlatform\Core\Bridge\Doctrine\Orm\Paginator:
    relations:
        - rel: create
          href:
            route: api_orders_post_collection
          exclusion:
            groups: ['OrderCollection']
            exclude_if:  expr(not is_granted('pintushi_order_create'))
        - rel: create
          href:
            route: api_products_post_collection
          exclusion:
            groups: ['ProductCollection']
            exclude_if:  expr(is_granted('pintushi_product_create') === false)
        - rel: create
          href:
            route: api_addresses_show_customer_addresses_collection
          exclusion:
            groups: ["CustomerAddressCollection"]
