services:
    pintushi.promotion_coupon_duration_eligibility_checker:
        class: Pintushi\Bundle\PromotionBundle\Checker\Eligibility\PromotionCouponDurationEligibilityChecker
        tags:
            - { name: 'pintushi.promotion_coupon_eligibility_checker'}

    pintushi.promotion_coupon_usage_limit_eligibility_checker:
        class: Pintushi\Bundle\PromotionBundle\Checker\Eligibility\PromotionCouponUsageLimitEligibilityChecker
        tags:
            - { name: 'pintushi.promotion_coupon_eligibility_checker'}
    pintushi.promotion_coupon_eligibility_checker:
        class: Pintushi\Bundle\PromotionBundle\Checker\Eligibility\CompositePromotionCouponEligibilityChecker

    pintushi.promotion_duration_eligibility_checker:
        class: Pintushi\Bundle\PromotionBundle\Checker\Eligibility\PromotionDurationEligibilityChecker
        tags:
            - { name: 'intushi.promotion_eligibility_checker' }

    pintushi.promotion_usage_limit_eligibility_checker:
        class: Pintushi\Bundle\PromotionBundle\Checker\Eligibility\PromotionUsageLimitEligibilityChecker
        tags:
            - { name: 'pintushi.promotion_eligibility_checker'}

    pintushi.promotion_subject_coupon_eligibility_checker:
        class: 'Pintushi\Bundle\PromotionBundle\Checker\Eligibility\PromotionSubjectCouponEligibilityChecker'
        arguments:
            - '@pintushi.promotion_coupon_eligibility_checker'
        tags:
            - { name: 'pintushi.promotion_eligibility_checker'}

    pintushi.promotion_rules_eligibility_checker:
        class: Pintushi\Bundle\PromotionBundle\Checker\Eligibility\PromotionRulesEligibilityChecker
        arguments:
            - '@pintushi.registry_promotion_rule_checker'
        tags:
            - { name: 'pintushi.promotion_eligibility_checker'}

    pintushi.promotion_eligibility_checker:
        class: Pintushi\Bundle\PromotionBundle\Checker\Eligibility\CompositePromotionEligibilityChecker

    Pintushi\Bundle\PromotionBundle\Checker\Eligibility\PromotionEligibilityCheckerInterface:
        alias: pintushi.promotion_eligibility_checker
