services:
    Pintushi\Bundle\PromotionBundle\Form\Type\PromotionType:
        public: true
        tags:
            - { name: "form.type" }

    Pintushi\Bundle\PromotionBundle\Form\Type\PromotionActionType:
        arguments:
            - 'Pintushi\Bundle\PromotionBundle\Entity\PromotionAction'
            - ['pintushi']
            - '@pintushi.form_registry.promotion_action'
        tags:
            - { name: "form.type" }

    Pintushi\Bundle\PromotionBundle\Form\Type\PromotionCouponType:
        arguments:
            - 'Pintushi\Bundle\PromotionBundle\Entity\PromotionCoupon'
            - ['pintushi']
        tags:
            - { name: "form.type" }

    Pintushi\Bundle\PromotionBundle\Form\Type\PromotionRuleCollectionType:
        arguments:
            - '@pintushi.registry_promotion_rule_checker'
        tags:
            - { name: "form.type" }

    pintushi.form.type.promotion_action.collection:
        class: Pintushi\Bundle\PromotionBundle\Form\Type\PromotionActionCollectionType
        arguments:
            - '@pintushi.registry_promotion_action'
        tags:
            - { name: 'form.type' }

    Pintushi\Bundle\PromotionBundle\Form\Type\PromotionRuleChoiceType:
        arguments:
            - '%pintushi.promotion_rules%'
        tags:
            - { name: "form.type" }

    Pintushi\Bundle\PromotionBundle\Form\Type\PromotionCouponToCodeType:
        arguments:
            - '@Pintushi\Bundle\PromotionBundle\Repository\PromotionCouponRepository'
        tags:
            - { name: "form.type" }

    Pintushi\Bundle\PromotionBundle\Form\Type\PromotionCouponGeneratorInstructionType:
        arguments:
            - 'Pintushi\Bundle\PromotionBundle\Generator\PromotionCouponGeneratorInstruction'
        tags:
            - { name: "form.type" }

    Pintushi\Bundle\PromotionBundle\Form\Type\PromotionRuleType:
        arguments:
            - 'Pintushi\Bundle\PromotionBundle\Entity\PromotionRule'
            - ['pintushi']
            - '@pintushi.form_registry.promotion_rule_checker'
        tags:
            - { name: "form.type" }

    Pintushi\Bundle\PromotionBundle\Form\Type\PromotionActionChoiceType:
        arguments:
            - '%pintushi.promotion_actions%'
        tags:
            - { name: "form.type" }
