services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\AddressBundle\:
        resource: '../../{Repository,DataFixtures,Command,Validator}'

    Pintushi\Component\Address\Comparator\AddressComparator: ~

    Pintushi\Bundle\AddressBundle\Form\Type\AddressType:
        arguments:
            - 'Pintushi\Bundle\AddressBundle\Entity\Address'
            - '@Pintushi\Bundle\AddressBundle\Form\EventSubscriber\AddressTypeSubscriber'
            - ['pintushi']
        tags:
            - { name: 'form.type'}

    Pintushi\Bundle\AddressBundle\Form\EventSubscriber\AddressTypeSubscriber: ~
