Pintushi\Bundle\TaxonomyBundle\Entity\Taxon:
    collectionOperations:
            post:
               denormalization_context:
                   groups: ["write"]
               access_control: is_granted('pintushi_taxon_create')
            get:
               acl_enabled: true
               access_control: is_granted('pintushi_taxon_view')
    itemOperations:
            get:
               access_control: is_granted('pintushi_taxon_view', object)
            put:
               access_control: is_granted('pintushi_taxon_edit', object)
            delete:
               access_control: is_granted('pintushi_taxon_delete', object)
    attributes:
        route_prefix: /admin
        normalization_context:
                   groups: ["read"]
        denormalization_context:
            groups: ["write"]
        validation_groups:  ["pintushi"]
