imports:
    - { resource: 'services/order_processing.yml'}

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\OrderBundle\:
        resource: '../../{Repository,DataFixtures,Command,Factory,Generator,NumberAssigner}'

    Pintushi\Bundle\OrderBundle\StateResolver\OrderPaymentStateResolver:
        public: true

    Pintushi\Bundle\OrderBundle\StateResolver\OrderShippingStateResolver:
        public: true

    Pintushi\Bundle\OrderBundle\StateResolver\OrderStateResolver:
        public: true

    pintushi.context.cart.new:
        class:  Pintushi\Component\Order\Context\CartContext
        tags:
            - { name: 'pintushi.context.cart', priority: -999 }

    pintushi.context.cart.composite:
        class: Pintushi\Component\Order\Context\CompositeCartContext

    pintushi.order_processing.order_processor.composite:
        class: Pintushi\Component\Order\Processor\CompositeOrderProcessor

    Pintushi\Bundle\OrderBundle\NumberGenerator\SequentialOrderNumberGenerator:
        arguments:
            - '@Pintushi\Bundle\OrderBundle\Repository\OrderSequenceRepository'

    Pintushi\Component\Order\Modifier\OrderItemQuantityModifier:
        public: true

    Pintushi\Component\Order\Processor\OrderProcessorInterface:
        alias: "pintushi.order_processing.order_processor"
        public: true

    Pintushi\Component\Order\Modifier\OrderModifier:
        arguments:
            - '@pintushi.order_processing.order_processor'
            - '@Pintushi\Component\Order\Modifier\OrderItemQuantityModifier'

    Pintushi\Bundle\OrderBundle\NumberAssigner\OrderNumberAssigner:
        public: true
        arguments:
            - '@Pintushi\Bundle\OrderBundle\NumberGenerator\SequentialOrderNumberGenerator'

    pintushi.adjustments_aggregator:
        class: Pintushi\Component\Order\Aggregator\AdjustmentsByLabelAggregator

    pintushi.expired_carts_remover:
        class:  Pintushi\Bundle\OrderBundle\Remover\ExpiredCartsRemover
        arguments:
            - '@Pintushi\Bundle\OrderBundle\Repository\OrderRepository'
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '%pintushi_order.cart_expiration_period%'

    Pintushi\Bundle\OrderBundle\Factory\AddToCartCommandFactory: ~

    Pintushi\Bundle\OrderBundle\Factory\AdjustmentFactory: ~

    SM\Factory\FactoryInterface: '@sm.factory'

    Pintushi\Component\Order\Repository\OrderRepositoryInterface: '@Pintushi\Bundle\OrderBundle\Repository\OrderRepository'

    Pintushi\Bundle\OrderBundle\Generator\RandomnessGeneratorInterface: '@Pintushi\Bundle\OrderBundle\Generator\RandomnessGenerator'

    Pintushi\Bundle\OrderBundle\TokenAssigner\UniqueIdBasedOrderTokenAssigner:
        public: true

    Pintushi\Bundle\OrderBundle\NumberAssigner\OrderNumberAssignerInterface: '@Pintushi\Bundle\OrderBundle\NumberAssigner\OrderNumberAssigner'
