payum:
    storages:
        Pintushi\Bundle\OrderBundle\Entity\Order: { doctrine: orm }
        Pintushi\Bundle\PaymentBundle\Entity\Payment: { doctrine: orm }
    security:
        token_storage:
            Pintushi\Bundle\PayumBundle\Entity\PaymentSecurityToken: { doctrine: orm }
    dynamic_gateways:
        config_storage:
            Pintushi\Bundle\PayumBundle\Entity\GatewayConfig: { doctrine: orm }
    gateways:
        cash_on_delivery:
            factory: offline
