Pintushi\Bundle\AutoBundle\Entity\CarBrand:
    attributes:
        id:
            groups: ['read', 'Details']
        name:
            groups: ['read', 'write', 'Details']
        organization:
            groups: ['read']
        image:
            groups: ['read', 'write', 'Details']
        firstLetter:
            groups: ['read', 'write', 'Details']

