Pintushi\Bundle\AutoBundle\Entity\CarModel:
    attributes:
        id:
            groups: ['read', 'write', 'Details']
        name:
            groups: ['read', 'write', 'Details']
        fullName:
            groups: ['read', 'Details']
        image:
            groups: ['read', 'Details']
        carSeries:
            groups: ['write']
