acls:
    pintushi_report_config_create:
        type: entity
        class: Pintushi\Bundle\ReportBundle\Entity\ReportConfigGroup
        label: '创建报告配置'
        permission: 'CREATE'
        category: "report_config"

    pintushi_report_config_view:
        type: entity
        class: Pintushi\Bundle\ReportBundle\Entity\ReportConfigGroup
        label: '查看报告配置'
        permission: 'VIEW'
        category: "report_config"

    pintushi_report_config_delete:
        type: entity
        class: Pintushi\Bundle\ReportBundle\Entity\ReportConfigGroup
        label: '查看报告配置'
        permission: 'DELETE'
        category: "report_config"

    pintushi_report_config_edit:
        type: entity
        class: Pintushi\Bundle\ReportBundle\Entity\ReportConfigGroup
        label: '编辑报告配置'
        permission: 'EDIT'
        category: "report_config"

    pintushi_report_create:
        type: entity
        class: Pintushi\Bundle\ReportBundle\Entity\Report
        label: '创建报告'
        permission: 'CREATE'
        category: "report"

    pintushi_report_view:
        type: entity
        class: Pintushi\Bundle\ReportBundle\Entity\Report
        label: '查看报告'
        permission: 'VIEW'
        category: "report"

    pintushi_report_delete:
        type: entity
        class: Pintushi\Bundle\ReportBundle\Entity\Report
        label: '查看报告'
        permission: 'DELETE'
        category: "report"

    pintushi_report_edit:
        type: entity
        class: Pintushi\Bundle\ReportBundle\Entity\Report
        label: '编辑报告'
        permission: 'EDIT'
        category: "report"
