Pintushi\Bundle\ReportBundle\Entity\ReportConfigItem:
    attributes:
        id:
            groups: ['read']
        name:
            groups: ['read', 'write']
        priority:
            groups: ['read', 'write']
        group:
            groups: [ 'read', 'write']
