services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\NavigationBundle\:
        resource: '../../{Repository,DataFixtures,Controller,Command}'

    Pintushi\Bundle\NavigationBundle\Config\MenuConfiguration:
      class: Pintushi\Bundle\NavigationBundle\Config\MenuConfiguration
      arguments:  ['@Pintushi\Bundle\NavigationBundle\Provider\ConfigurationProvider']

    Pintushi\Bundle\NavigationBundle\Menu\ConfigurationBuilder:
      class: Pintushi\Bundle\NavigationBundle\Menu\ConfigurationBuilder
      arguments:
        - '@pintushi_menu.configuration_resolver'
        - '@pintushi_menu.factory'
        - '@event_dispatcher'
        - '@Pintushi\Bundle\NavigationBundle\Config\MenuConfiguration'
      tags:
            - { name: pintushi_menu.builder }

    Pintushi\Bundle\NavigationBundle\Provider\ConfigurationProvider:
      class: Pintushi\Bundle\NavigationBundle\Provider\ConfigurationProvider
      arguments: ['@pintushi.cache.provider.navigation']

    pintushi.cache.provider.navigation:
        parent: doctrine_cache.abstract.chain
        autoconfigure: false
        autowire: false
        public: true
        calls:
        - [ setNamespace, [ 'pintushi_navigation' ] ]

    pintushi_menu.array_loader:
        class: 'Knp\Menu\Loader\ArrayLoader'
        public: false
        arguments:
            - "@pintushi_menu.factory"

    pintushi_menu.manipulator:
        class: 'Knp\Menu\Util\MenuManipulator'
        public: false

    Pintushi\Bundle\NavigationBundle\Provider\BuilderChainProvider:
      class: Pintushi\Bundle\NavigationBundle\Provider\BuilderChainProvider
      arguments:
          - '@pintushi_menu.factory'
          - '@pintushi_menu.array_loader'
          - '@pintushi_menu.manipulator'
      tags:
          - { name: knp_menu.provider }

    pintushi_menu.factory:
        class: 'Knp\Menu\MenuFactory'

    pintushi_menu.configuration_resolver:
        class: 'Pintushi\Component\Config\Resolver\SystemAwareResolver'
        arguments:
            - '@service_container'

    pintushi_navigation.menu_extension.routing:
        class: 'Pintushi\Bundle\NavigationBundle\Menu\RoutingAwareMenuFactoryExtension'
        arguments:
            - '@router.default'
        tags:
            - { name: pintushi_navigation.menu_extension, priority: 110 }

    pintushi_navigation.menu_extension.acl:
        class: 'Pintushi\Bundle\NavigationBundle\Menu\AclAwareMenuFactoryExtension'
        arguments:
            - '@router.default'
            - '@security.authorization_checker'
            - '@pintushi_security.class_authorization_checker'
            - '@pintushi_security.token_accessor'
            - '@logger'
        tags:
            - { name: pintushi_navigation.menu_extension, priority: 110 }
