placeholders:
    placeholders:
        scripts_before:
            items:
                template_datagrid_toolbar:
                    order: 20

    items:
        template_datagrid_toolbar:
            applicable: "@oro_layout.helper->isTemplateRequest()"
            template: PintushiGridBundle:js:toolbar.html.twig
