system_configuration:
    groups:
        look_and_feel:
            title:       pintushi.grid.system_configuration.groups.look_and_feel.title
            icon:        'fa-eye'
            page_reload: true

        grid_settings:
            title:       pintushi.grid.system_configuration.groups.grid_settings.title

    fields:
        pintushi_grid.default_per_page:
            data_type: integer
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            priority: 200
            options:
                label: pintushi.grid.system_configuration.fields.default_per_page.label
                choices:
                    10:     10
                    25:     25
                    50:     50
                    100:    100
                required: true
                constraints:
                    - NotBlank: ~
        pintushi_grid.full_screen_layout_enabled:
            data_type: boolean
            type: Pintushi\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 150
            options:
                label: pintushi.grid.system_configuration.fields.full_screen_layout_enabled.label
                tooltip: pintushi.grid.system_configuration.fields.full_screen_layout_enabled.tooltip
                required: false
    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            look_and_feel:
                                priority: 210
                                children:
                                    grid_settings:
                                        children:
                                            - pintushi_grid.default_per_page
                                            - pintushi_grid.full_screen_layout_enabled
        user_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            look_and_feel:
                                priority: 210
                                children:
                                    grid_settings:
                                        children:
                                            - pintushi_grid.default_per_page
                                            - pintushi_grid.full_screen_layout_enabled

    section_tree:
        look-and-feel:
            pintushi_grid.default_per_page: ~
