Pintushi\Bundle\CustomerBundle\Entity\Customer:
    attributes:
        id:
            groups: ['read', 'Details', 'OrderReview']
        email:
            groups: ['read', 'write', 'Details']
        fullName:
            groups: ['read', 'Details', 'OrderReview']
        phoneNumber:
            groups: ['read', 'create', 'Details']
        emailCanonical:
            groups: ['read']
        firstName:
            groups: ['read', 'write', 'Details']
        lastName:
            groups: ['read', 'write', 'Details']
        gender:
            groups: ['read', 'write', 'Details', 'OrderReview']
            max_depth: 1
        birthday:
            groups: ['read', 'write', 'Details']
        group:
            groups: ['read', 'write', 'Details']
        organization:
            groups: ['write', 'read']
        plainPassword:
            groups: [ 'write', 'read']
        defaultAuto:
            groups: [ 'Details']
