Pintushi\Bundle\CustomerBundle\Entity\Customer:
    collectionOperations:
            post:
               access_control: is_granted('pintushi_customer_create')
               validation_groups:  ["create", "pintushi"]
               denormalization_context:
                    groups: ["write", "create"]
            get:
               acl_enabled: true
               access_control: is_granted('pintushi_customer_view')
    itemOperations:
           put:
               access_control: is_granted('pintushi_customer_edit', object)
           get:
               access_control: is_granted('pintushi_customer_view', object)
           delete:
               access_control: is_granted('pintushi_customer_delete', object)
    attributes:
        normalization_context:
            groups: ["read"]
            enable_max_depth: true
        denormalization_context:
            groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin

Pintushi\Bundle\CustomerBundle\Entity\CustomerGroup:
    collectionOperations:
            post:
               access_control: is_granted('pintushi_customer_group_create')
            get:
               acl_enabled: true
               access_control: is_granted('pintushi_customer_group_view')
    itemOperations:
           put:
               access_control: is_granted('pintushi_customer_group_edit', object)
           get:
               access_control: is_granted('pintushi_customer_group_view', object)
           delete:
               access_control: is_granted('pintushi_customer_group_delete', object)
    attributes:
        normalization_context:
            groups: ["read"]
        denormalization_context:
            groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin
