services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\ReportBundle\:
        resource: '../../{Repository,DataFixtures,Command,Provider}'

    Pintushi\Bundle\ReportBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
