services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\ReportBundle\:
        resource: '../../{Repository,DataFixtures,Command,Provider}'
