Pintushi\Bundle\PaymentBundle\Entity\Payment:
    attributes:
        id:
            groups: ['Details']
        method:
            groups: ['Details']
        amount:
            groups: ['Details']
        currencyCode:
            groups: ['Details']
        state:
            groups: ['Details']
