Pintushi\Bundle\PaymentBundle\Entity\PaymentMethod:
    attributes:
        id:
            groups: ['read', 'Details']
        name:
            groups: ['read', 'write', 'Details']
        description:
            groups: ['read', 'write', 'Details']
        instructions:
            groups: ['read', 'write']
        position:
            groups: ['read', 'write', 'Details']
        environment:
            groups: ['read', 'write']
        gatewayConfig:
            groups: ['read', 'write']

