Pintushi\Bundle\MaintenanceBundle\Entity\Service:
    collectionOperations:
            post:
               access_control: is_granted('pintushi_service_create')
            get:
               acl_enabled: true
               access_control: is_granted('pintushi_service_view')
    itemOperations:
           put:
               access_control: is_granted('pintushi_service_edit', object)
           get:
               access_control: is_granted('pintushi_service_view', object)
           delete:
               access_control: is_granted('pintushi_service_delete', object)
    attributes:
        normalization_context:
            groups: ["read"]
        denormalization_context:
            groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin

Pintushi\Bundle\MaintenanceBundle\Entity\ServiceGroup:
    collectionOperations:
            post:
               access_control: is_granted('pintushi_service_group_create')
            get:
               acl_enabled: true
               access_control: is_granted('pintushi_service_group_view')
    itemOperations:
           put:
               access_control: is_granted('pintushi_service_group_edit', object)
           get:
               access_control: is_granted('pintushi_service_group_view', object)
           delete:
               access_control: is_granted('pintushi_service_group_delete', object)
    attributes:
        normalization_context:
            groups: ["read"]
        denormalization_context:
            groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin


Pintushi\Bundle\MaintenanceBundle\Entity\ServiceBlock:
    collectionOperations:
            post:
               access_control: is_granted('pintushi_service_block_create')
            get:
               acl_enabled: true
               access_control: is_granted('pintushi_service_block_view')
    itemOperations:
           put:
               access_control: is_granted('pintushi_service_block_edit', object)
           get:
               access_control: is_granted('pintushi_service_block_view', object)
           delete:
               access_control: is_granted('pintushi_service_block_delete', object)
    attributes:
        normalization_context:
            groups: ["Details"]
        denormalization_context:
            groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin
