acls:
    pintushi_order_review_create:
        type: entity
        class: Pintushi\Bundle\ReviewBundle\Entity\OrderReview
        label: '创建评论'
        permission: 'CREATE'
        category: "order_review"

    pintushi_order_review_view:
        type: entity
        class: Pintushi\Bundle\ReviewBundle\Entity\OrderReview
        label: '查看评论'
        permission: 'VIEW'
        category: "order_review"

    pintushi_order_review_delete:
        type: entity
        class: Pintushi\Bundle\ReviewBundle\Entity\OrderReview
        label: '查看评论'
        permission: 'DELETE'
        category: "order_review"

    pintushi_order_review_edit:
        type: entity
        class: Pintushi\Bundle\ReviewBundle\Entity\OrderReview
        label: '编辑评论'
        permission: 'EDIT'
        category: "order_review"
