Pintushi\Bundle\AddressBundle\Entity\Address:
    properties:
        provinceCode:
            - NotBlank: { groups: ["pintushi"]}
        cityCode:
            - NotBlank: { groups: ["pintushi"]}
        regionCode:
            - NotBlank: { groups: ["pintushi"]}
        phoneNumber:
            - NotBlank: { groups: ["extra"]}
        username:
            - NotBlank: { groups: ["extra"]}
            - Length:   { groups: ["extra"], max: 30}
        street:
            - NotBlank: { groups: ["pintushi"]}
            - Length:   { groups: ["pintushi"], max: 100}
