services:
    Pintushi\Bundle\PaymentBundle\Form\Type\PaymentType:
        tags:
            - { name: form.type }
        arguments: ['Pintushi\Bundle\PaymentBundle\Entity\Payment', ['pintushi']]

    Pintushi\Bundle\PaymentBundle\Form\Type\PaymentMethodType:
        tags:
            - { name: form.type }
        arguments:
            - 'Pintushi\Bundle\PaymentBundle\Entity\PaymentMethod'
            - ['pintushi']
            - '@Overtrue\Pinyin\Pinyin'

    Pintushi\Bundle\PaymentBundle\Form\Type\PaymentMethodChoiceType:
        tags:
            - { name: form.type }
        arguments: ['@pintushi.payment_methods_resolver', 'Pintushi\Bundle\PaymentBundle\Repository\PaymentMethodRepository']

    Pintushi\Bundle\PaymentBundle\Form\Type\PaymentGatewayChoiceType:
        tags:
            - { name: form.type }
        arguments: ['%pintushi.payment_gateways%']
