imports:
    - { resource: 'form.yml'}

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\PaymentBundle\:
        resource: '../../{Repository,DataFixtures,Command,Factory}'

    pintushi.registry.payment_methods_resolver:
        class: Sylius\Component\Registry\PrioritizedServiceRegistry
        arguments:
            - 'Pintushi\Bundle\PaymentBundle\Resolver\PaymentMethodsResolverInterface'
            - 'Payment methods resolver'

    pintushi.payment_methods_resolver:
        class: Pintushi\Bundle\PaymentBundle\Resolver\CompositeMethodsResolver
        arguments:
            - '@pintushi.registry.payment_methods_resolver'

    pintushi.payment_methods_resolver.default:
        class: Pintushi\Bundle\PaymentBundle\Resolver\PaymentMethodsResolver
        arguments:
            - '@Pintushi\Bundle\PaymentBundle\Repository\PaymentMethodRepository'
        tags:
            -  { name: "pintushi.payment_method_resolver", type: "default", label: "Default" }

    PaymentMethodRepositoryInterface: '@Pintushi\Bundle\PaymentBundle\Repository\PaymentMethodRepository'

    Pintushi\Bundle\PaymentBundle\Resolver\DefaultPaymentMethodResolver: ~

    Pintushi\Bundle\PaymentBundle\Resolver\DefaultPaymentMethodResolverInterface: '@Pintushi\Bundle\PaymentBundle\Resolver\DefaultPaymentMethodResolver'

    Pintushi\Bundle\PaymentBundle\Factory\PaymentFactoryInterface: '@Pintushi\Bundle\PaymentBundle\Factory\PaymentFactory'
