services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Pintushi\Bundle\InventoryBundle\:
        resource: '../../{Repository,DataFixtures,Command,Operator}'

    Pintushi\Bundle\InventoryBundle\Checker\AvailabilityChecker: ~

    Pintushi\Bundle\InventoryBundle\Validator\Constraints\InStockValidator:
        arguments:
            - '@Pintushi\Bundle\InventoryBundle\Checker\AvailabilityChecker'
        tags:
            - {name: validator.constraint_validator, alias: 'pintushi_in_stock' }

    Pintushi\Bundle\InventoryBundle\Checker\AvailabilityCheckerInterface: '@Pintushi\Bundle\InventoryBundle\Checker\AvailabilityChecker'
