Pintushi\Bundle\ShippingBundle\Entity\ShippingMethod:
    attributes:
        id:
            groups: ['read', 'write', 'Details']
        name:
            groups: ['read', 'write', 'Details']
        amount:
            groups: ['read', 'write', 'Details']
        type:
            groups: ['read', 'Details']
        enabled:
            groups: ['read', 'write']
        description:
            groups: ['read', 'write', 'Details']
        position:
            groups: ['read', 'write', 'Details']
