imports:
    - { resource: 'services/eligibility_checkers.yml'}
    - { resource: 'services/forms.yml'}
    - { resource: 'services/promotion.yml'}

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\PromotionBundle\:
        resource: '../../{Repository,DataFixtures,Command}'

    Pintushi\Bundle\PromotionBundle\Modifier\OrderPromotionsUsageModifier:
        public: true

    Pintushi\Bundle\PromotionBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Pintushi\Bundle\PromotionBundle\Factory\PromotionCouponFactory: ~

    pintushi.promotion_processor:
        class: Pintushi\Bundle\PromotionBundle\Processor\PromotionProcessor
        arguments:
            - '@pintushi.active_promotions_provider'
            - '@pintushi.promotion_eligibility_checker'
            - '@pintushi.promotion_applicator'

    pintushi.registry_promotion_action:
        class: Sylius\Component\Registry\ServiceRegistry
        arguments:
            - 'Pintushi\Bundle\PromotionBundle\Action\PromotionActionCommandInterface'
            - 'promotion action'

    pintushi.promotion_applicator:
        class: Pintushi\Bundle\PromotionBundle\Action\PromotionApplicator
        arguments:
            - '@pintushi.registry_promotion_action'

    pintushi.registry_promotion_rule_checker:
        class:  Sylius\Component\Registry\ServiceRegistry
        arguments:
            - 'Pintushi\Bundle\PromotionBundle\Checker\Rule\RuleCheckerInterface'
            - 'rule checker'

    pintushi.active_promotions_provider:
        class: Pintushi\Bundle\PromotionBundle\Provider\ActivePromotionsProvider
        arguments:
            - '@Pintushi\Bundle\PromotionBundle\Repository\PromotionRepository'

    Pintushi\Bundle\PromotionBundle\Factory\PromotionCouponFactory: ~

    Pintushi\Bundle\PromotionBundle\Generator\PromotionCouponGenerator:
        arguments:
            - '@Pintushi\Bundle\PromotionBundle\Factory\PromotionCouponFactory'
            - '@Pintushi\Bundle\PromotionBundle\Repository\PromotionCouponRepository'
            - '@doctrine.orm.entity_manager'
            - '@pintushi.promotion_coupon_generator.percentage_policy'

    pintushi.promotion_coupon_generator.percentage_policy:
        class: Pintushi\Bundle\PromotionBundle\Generator\PercentageGenerationPolicy
        arguments:
            - '@Pintushi\Bundle\PromotionBundle\Repository\PromotionCouponRepository'

    pintushi.validator.promotion_subject_coupon:
        class: Pintushi\Bundle\PromotionBundle\Validator\PromotionSubjectCouponValidator
        arguments:
            - '@pintushi.promotion_eligibility_checker'
        tags:
            - { name: 'validator.constraint_validator' , alias: 'pintushi_promotion_subject_validator'}

    pintushi.validator.date_range:
        class:  Pintushi\Bundle\PromotionBundle\Validator\PromotionDateRangeValidator
        tags:
            - { name: 'validator.constraint_validator', alias: 'pintushi_promotion_date_range_validator' }

    pintushi.validator.promotion_coupon_generation_amount:
        class: Pintushi\Bundle\PromotionBundle\Validator\CouponGenerationAmountValidator
        arguments:
            - '@pintushi.promotion_coupon_generator.percentage_policy'
        tags:
            - { name: 'validator.constraint_validator',  alias: 'pintushi_coupon_generation_amount_validator'}

    pintushi.form_registry.promotion_action:
        class: Pintushi\Bundle\CoreBundle\Form\Registry\FormTypeRegistry

    pintushi.form_registry.promotion_rule_checker:
        class: Pintushi\Bundle\CoreBundle\Form\Registry\FormTypeRegistry

    pintushi.integer_distributor:
        class: Pintushi\Bundle\PromotionBundle\Distributor\IntegerDistributor

    pintushi.proportional_integer_distributor:
        class: Pintushi\Bundle\PromotionBundle\Distributor\ProportionalIntegerDistributor

