services:
    Pintushi\Bundle\CoreBundle\Faker\Provider\EntityReferenceProvider:
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: 'nelmio_alice.faker.provider' }
