# ObjectNormalizer can't normalize MenuItem, because MenuItem implements \Traversable
# we have to find another way to turn camelCase to snake case
Knp\Menu\MenuItem:
    attributes:
        name:
            groups: ['read']
        label:
            groups: ['read', 'write']
        linkAttributes:
            groups: [ 'write']
        childrenAttributes:
            groups: ['read']
        labelAttributes:
            groups: ['read']
        uri:
            groups: ['read']
        attributes:
            groups: ['read']
        extras:
            groups: ['read']
        children:
            groups: ['read']
        isCurrent:
            groups: ['read', 'write']
