services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\LocationBundle\:
        resource: '../../{Repository,DataFixtures,Command}'

    Pintushi\Bundle\LocationBundle\Orm\Extension\LocationQueryBuilderExtension:
        calls:
            - [setRequest, ["@=service('request_stack').getCurrentRequest()"]]
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
