Pintushi\Bundle\LocationBundle\Entity\Location:
    constraints:
        - Pintushi\Bundle\TaxonomyBundle\Validator\Constraints\ParentTaxon:  { groups: ['pintushi'], 'message': '不能设置自身为父级'}
    properties:
        name:
            - NotBlank: { groups: ['pintushi'] }
            - Length: { groups: ['pintushi'] , max: 40}
        code:
            - NotBlank: { groups: ['pintushi'] }
            - Length: { groups: ['pintushi'] , max: 40}
