acls:
    pintushi_payment_method_create:
        type: entity
        class: Pintushi\Bundle\PaymentBundle\Entity\PaymentMethod
        label: '创建付款方式'
        permission: 'CREATE'
        category: "payment"

    pintushi_payment_method_view:
        type: entity
        class: Pintushi\Bundle\PaymentBundle\Entity\PaymentMethod
        label: '查看付款方式'
        permission: 'VIEW'
        category: "payment"

    pintushi_payment_method_delete:
        type: entity
        class: Pintushi\Bundle\PaymentBundle\Entity\PaymentMethod
        label: '查看付款方式'
        permission: 'DELETE'
        category: "payment"

    pintushi_payment_method_edit:
        type: entity
        class: Pintushi\Bundle\PaymentBundle\Entity\PaymentMethod
        label: '编辑付款方式'
        permission: 'EDIT'
        category: "payment"
