services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\AutoBundle\:
        resource: '../../{Repository,DataFixtures,Command}'

    Overtrue\Pinyin\Pinyin: ~

    Pintushi\Bundle\AutoBundle\EventListener\CarBrandListener:
        arguments: ['@Overtrue\Pinyin\Pinyin']
        tags:
          - { name: 'doctrine.event_listener', event: 'prePersist', lazy: true }
          - { name: 'doctrine.event_listener', event: 'preUpdate', lazy: true }

    Pintushi\Bundle\AutoBundle\Serializer\CarSeriesIdDenormalizer:
        arguments:
            - '@Pintushi\Bundle\AutoBundle\Repository\CarSeriesRepository'
        tags:
            - { name: 'serializer.denormalizer', priority: 32}
