services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    Pintushi\Bundle\FormBundle\Form\Type\SelectHiddenType: ~

    Pintushi\Bundle\FormBundle\Form\Type\SelectChoiceType: ~

    Pintushi\Bundle\FormBundle\Form\Type\SelectEntityType: ~

    Pintushi\Bundle\FormBundle\Form\Type\SelectHiddenAutocompleteType: ~

    Pintushi\Bundle\FormBundle\Form\Transformer\SelectHiddenAutocompleteTransfomer:
        tags:
            - { name: 'liform.transformer', form_type: 'pintushi_select_hidden_autocomplete', widget: 'autocomplete'}

    Pintushi\Bundle\FormBundle\Form\Transformer\HiddenTransformer:
        tags:
            - { name: 'liform.transformer', form_type: 'hidden', widget: 'input'}
