imports:
    - { resource: 'form_type.yml'}

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\FormBundle\:
        resource: '../../{Repository,Command,Validator,Controller}'

    Pintushi\Bundle\FormBundle\Autocomplete\SearchRegistry: ~

    Pintushi\Bundle\FormBundle\Autocomplete\Security: ~

    Pintushi\Bundle\FormBundle\Autocomplete\SearchHandler:
        abstract: true
        calls:
            - [initSearchIndexer, ["@pintushi_search.index", '@Pintushi\Bundle\SearchBundle\Provider\SearchMappingProvider']]
            - [initDoctrinePropertiesByManagerRegistry, ["@doctrine"]]
            - [setAclHelper,["@pintushi.acl_helper"]]
