Pintushi\Bundle\AutoBundle\Entity\CarBrand:
    collectionOperations:
           post:
               access_control: is_granted('pintushi_auto_create')
           get:
               acl_enabled: true
               access_control: is_granted('pintushi_auto_view')
    itemOperations:
           put:
               access_control: is_granted('pintushi_auto_edit', object)
           get:
               access_control: is_granted('pintushi_auto_view', object)
           delete:
               access_control: is_granted('pintushi_auto_delete', object)
    subresourceOperations:
        api_car_brands_car_series_get_subresource:
            method: 'GET'
            acl_enabled: true
            access_control: is_granted('pintushi_auto_view', $object)
    attributes:
        normalization_context:
             groups: ["read"]
        denormalization_context:
           groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin
    properties:
        carSeries:
            subresource:
                resourceClass: 'Pintushi\Bundle\AutoBundle\Entity\CarSeries'
                collection: true
                maxDepth: 1

Pintushi\Bundle\AutoBundle\Entity\CarSeries:
    collectionOperations:
           post:
               access_control: is_granted('pintushi_auto_create', object.getBrand())
    itemOperations:
           put:
               access_control: is_granted('pintushi_auto_edit', object.getBrand())
           get:
               access_control: is_granted('pintushi_auto_view', object.getBrand())
           delete:
               access_control: is_granted('pintushi_auto_delete', object.getBrand())
    subresourceOperations:
        api_car_series_car_models_get_subresource:
            method: 'GET'
            acl_enabled: true
            access_control: is_granted('pintushi_auto_view', object.getBrand())
    attributes:
        normalization_context:
             groups: ["read"]
        denormalization_context:
           groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin
    properties:
        carModels:
            subresource:
                resourceClass: 'Pintushi\Bundle\AutoBundle\Entity\CarModel'
                collection: true

Pintushi\Bundle\AutoBundle\Entity\CarModel:
    collectionOperations:
           post:
               path: /admin/car_models
               access_control: is_granted('pintushi_auto_create', object.getCarSeries().getBrand())
    itemOperations:
           put:
               path: /admin/car_models/{id}
               access_control: is_granted('pintushi_auto_edit', object.getCarSeries().getBrand())
           get:
               path: /admin/car_models/{id}
               access_control: is_granted('pintushi_auto_view', object.getCarSeries().getBrand())
           delete:
               path: /admin/car_models/{id}
               access_control: is_granted('pintushi_auto_delete', object.getCarSeries().getBrand())
    attributes:
        normalization_context:
             groups: ["read"]
        denormalization_context:
           groups: ["write"]
        validation_groups:  ["pintushi"]
